"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { BookOpen, Building2, ChevronRight, GraduationCap, Layers, LayoutDashboard, LogOut, Users, Hash, Loader2 } from "lucide-react";
import { adminApi } from "../../../lib/api/admin";

type Entity = Record<string, unknown> & { id: string; isActive?: boolean; name?: string; number?: number; room?: { id: string } | null; university?: { name: string }; department?: { name: string } };
const nav = [["/admin", "Overview", LayoutDashboard], ["/admin/universities", "Universities", Building2], ["/admin/departments", "Departments", GraduationCap], ["/admin/semesters", "Semesters", Layers], ["/admin/channels", "Channels", Hash], ["/admin/users", "Students", Users]] as const;

export function AdminLogin() {
  const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(""); try { await adminApi.login(username, password); router.replace("/admin"); } catch { setError("Invalid admin credentials."); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-4"><form onSubmit={submit} className="w-full max-w-sm rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><div className="mb-6 flex items-center gap-2 text-lg font-semibold"><BookOpen className="text-blue-600" /> StudyVerse Admin</div><h1 className="text-xl font-semibold">Sign in</h1><p className="mt-1 text-sm text-slate-500">Use your administrator account.</p>{error && <p className="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="mt-5 block text-sm font-medium">Username<input value={username} onChange={e => setUsername(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5" required /></label><label className="mt-4 block text-sm font-medium">Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5" required /></label><button disabled={loading} className="mt-6 flex w-full justify-center rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60">{loading ? <Loader2 className="h-5 w-5 animate-spin" /> : "Sign in"}</button></form></main>;
}

export function AdminApp({ section = "overview" }: { section?: "overview" | "universities" | "departments" | "semesters" | "channels" | "users" }) {
  const router = useRouter(), pathname = usePathname(); const [ready, setReady] = useState(false); const [error, setError] = useState("");
  useEffect(() => { adminApi.me().then(() => setReady(true)).catch(() => router.replace("/admin/login")); }, [router]);
  if (!ready) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="animate-spin text-blue-600" /></div>;
  async function logout() { try { await adminApi.logout(); } finally { router.replace("/admin/login"); } }
  return <div className="min-h-screen bg-slate-50 lg:flex"><aside className="border-b bg-slate-950 p-4 text-slate-200 lg:min-h-screen lg:w-60 lg:border-b-0"><Link href="/admin" className="mb-6 flex items-center gap-2 font-semibold text-white"><BookOpen className="text-blue-400"/>StudyVerse Admin</Link><nav className="flex gap-1 overflow-x-auto lg:flex-col">{nav.map(([href, label, Icon]) => <Link key={href} href={href} className={`flex shrink-0 items-center gap-2 rounded-md px-3 py-2 text-sm ${pathname === href ? "bg-blue-600 text-white" : "hover:bg-slate-800"}`}><Icon className="h-4 w-4"/>{label}</Link>)}</nav><button onClick={logout} className="mt-5 flex items-center gap-2 px-3 py-2 text-sm text-slate-300 hover:text-white"><LogOut className="h-4 w-4"/>Sign out</button></aside><main className="min-w-0 flex-1 p-5 sm:p-8">{section === "overview" ? <Overview /> : <Management section={section} reportError={setError} />}{error && <p className="fixed bottom-4 right-4 rounded bg-red-600 px-4 py-2 text-sm text-white">{error}</p>}</main></div>;
}

function Overview() { const [stats, setStats] = useState<Record<string, number> | null>(null); useEffect(() => { adminApi.stats().then(setStats); }, []); const labels: Record<string, string> = { universities: "Universities", departments: "Departments", semesters: "Semesters", rooms: "Study rooms", channels: "Channels", students: "Students" }; return <><h1 className="text-2xl font-semibold">Admin overview</h1><p className="mt-1 text-sm text-slate-500">Live academic-structure data from StudyVerse.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats ? Object.entries(stats).map(([key, value]) => <div key={key} className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">{labels[key]}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>) : <Loader2 className="animate-spin text-blue-600"/>}</div></> }

function Management({ section, reportError }: { section: Exclude<Parameters<typeof AdminApp>[0]["section"], "overview" | undefined>; reportError: (e: string) => void }) {
  const configs = { universities: { title: "Universities", path: "universities", fields: ["name", "code"] }, departments: { title: "Departments", path: "departments", fields: ["name", "universityId"] }, semesters: { title: "Semesters", path: "semesters", fields: ["number", "departmentId"] }, channels: { title: "Channels", path: "channels", fields: ["name", "roomId", "description"] }, users: { title: "Students", path: "users", fields: [] } } as const;
  const config = configs[section]; const [items, setItems] = useState<Entity[]>([]); const [form, setForm] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); adminApi.list<Entity>(config.path).then(setItems).catch(() => reportError(`Unable to load ${config.title.toLowerCase()}.`)).finally(() => setLoading(false)); }; useEffect(load, [section]);
  async function create(e: FormEvent) { e.preventDefault(); try { await adminApi.create(config.path, Object.fromEntries(Object.entries(form).map(([k,v]) => [k, k === "number" ? Number(v) : v]))); setForm({}); load(); } catch { reportError("Could not save this record. Check the related ID and uniqueness."); } }
  async function toggle(item: Entity) { try { await adminApi.update(config.path, item.id, { isActive: !item.isActive }); load(); } catch { reportError("Could not update status."); } }
  async function edit(item: Entity) { const field = section === "semesters" ? "number" : "name"; const current = String(item[field] ?? ""); const value = window.prompt(`Update ${field}`, current); if (value === null || value.trim() === current) return; try { await adminApi.update(config.path, item.id, { [field]: field === "number" ? Number(value) : value.trim() }); load(); } catch { reportError("Could not update this record."); } }
  async function remove(item: Entity) { if (!confirm("Delete this channel permanently?")) return; try { await adminApi.remove(config.path, item.id); load(); } catch { reportError("Could not delete this record."); } }
  return <><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">{config.title}</h1><p className="mt-1 text-sm text-slate-500">Manage real StudyVerse {config.title.toLowerCase()}.</p></div></div>{section !== "users" && <form onSubmit={create} className="mt-6 grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4">{config.fields.map(field => <input key={field} required={field !== "description"} placeholder={field === "roomId" || field === "departmentId" || field === "universityId" ? `${field} (UUID)` : field} value={form[field] ?? ""} onChange={e => setForm({ ...form, [field]: e.target.value })} className="rounded-lg border px-3 py-2 text-sm"/>)}<button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Add</button></form>}<div className="mt-6 overflow-hidden rounded-xl border bg-white">{loading ? <div className="p-8"><Loader2 className="animate-spin text-blue-600"/></div> : items.length === 0 ? <p className="p-8 text-sm text-slate-500">No {config.title.toLowerCase()} found.</p> : <ul className="divide-y">{items.map(item => <li key={item.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="font-medium">{item.name ?? `Semester ${item.number}`}</p><p className="text-xs text-slate-500">{item.email as string ?? item.university?.name ?? item.department?.name ?? item.id}</p></div>{section !== "users" && <button onClick={() => edit(item)} className="text-sm text-blue-600">Edit</button>}{item.isActive !== undefined && <button onClick={() => toggle(item)} className={`rounded px-2 py-1 text-xs ${item.isActive ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{item.isActive ? "Active" : "Archived"}</button>}{section === "channels" && <button onClick={() => remove(item)} className="text-sm text-red-600">Delete</button>}<ChevronRight className="h-4 w-4 text-slate-400"/></li>)}</ul>}</div></>;
}
