import { NextFunction, Request, Response } from "express";
import { prisma } from "@repo/db/prisma";
import { isValidUuid } from "../../utils/validation";
import { ensureRoomChannels } from "../channels";

const fail = (res: Response, message: string, status = 400) => res.status(status).json({ error: message });
const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
const validId = (res: Response, id?: string) => id && isValidUuid(id) ? true : (fail(res, "Valid ID is required"), false);

export const adminMe = async (_req: Request, res: Response, next: NextFunction) => { try { res.json({ ok: true }); } catch (e) { next(e); } };
export const stats = async (_req: Request, res: Response, next: NextFunction) => { try {
  const [universities, departments, semesters, rooms, channels, students] = await Promise.all([prisma.university.count(), prisma.department.count(), prisma.semester.count(), prisma.room.count(), prisma.channel.count(), prisma.user.count()]);
  res.json({ universities, departments, semesters, rooms, channels, students });
} catch (e) { next(e); } };

export const listUniversities = async (_req: Request, res: Response, next: NextFunction) => { try { res.json(await prisma.university.findMany({ include: { _count: { select: { departments: true, users: true } } }, orderBy: { name: "asc" } })); } catch (e) { next(e); } };
export const createUniversityAdmin = async (req: Request, res: Response, next: NextFunction) => { try { const name = text(req.body.name), code = text(req.body.code) || null; if (!name) return fail(res, "University name is required"); res.status(201).json(await prisma.university.create({ data: { name, code } })); } catch (e) { next(e); } };
export const updateUniversity = async (req: Request, res: Response, next: NextFunction) => { try { if (!validId(res, req.params.id)) return; const data: { name?: string; code?: string | null; isActive?: boolean } = {}; if (req.body.name !== undefined) { const name = text(req.body.name); if (!name) return fail(res, "University name is required"); data.name = name; } if (req.body.code !== undefined) data.code = text(req.body.code) || null; if (typeof req.body.isActive === "boolean") data.isActive = req.body.isActive; res.json(await prisma.university.update({ where: { id: req.params.id! }, data })); } catch (e) { next(e); } };

export const listDepartments = async (req: Request, res: Response, next: NextFunction) => { try { const universityId = req.query.universityId as string | undefined; res.json(await prisma.department.findMany({ where: universityId ? { universityId } : {}, include: { university: true, _count: { select: { semesters: true, users: true } } }, orderBy: { name: "asc" } })); } catch (e) { next(e); } };
export const createDepartment = async (req: Request, res: Response, next: NextFunction) => { try { const name = text(req.body.name), universityId = text(req.body.universityId); if (!name || !isValidUuid(universityId)) return fail(res, "Name and university are required"); res.status(201).json(await prisma.department.create({ data: { name, universityId } })); } catch (e) { next(e); } };
export const updateDepartment = async (req: Request, res: Response, next: NextFunction) => { try { if (!validId(res, req.params.id)) return; const data: { name?: string; universityId?: string; isActive?: boolean } = {}; if (req.body.name !== undefined) { const name = text(req.body.name); if (!name) return fail(res, "Department name is required"); data.name = name; } if (req.body.universityId !== undefined && isValidUuid(req.body.universityId)) data.universityId = req.body.universityId; if (typeof req.body.isActive === "boolean") data.isActive = req.body.isActive; res.json(await prisma.department.update({ where: { id: req.params.id! }, data })); } catch (e) { next(e); } };

export const listSemesters = async (req: Request, res: Response, next: NextFunction) => { try { const departmentId = req.query.departmentId as string | undefined; res.json(await prisma.semester.findMany({ where: departmentId ? { departmentId } : {}, include: { department: { include: { university: true } }, room: { include: { _count: { select: { members: true, channels: true } } } } }, orderBy: { number: "asc" } })); } catch (e) { next(e); } };
export const createSemester = async (req: Request, res: Response, next: NextFunction) => { try { const departmentId = text(req.body.departmentId), number = Number(req.body.number); if (!isValidUuid(departmentId) || !Number.isInteger(number) || number < 1) return fail(res, "Valid department and semester number are required"); const semester = await prisma.semester.create({ data: { departmentId, number }, include: { department: true } }); const room = await prisma.room.create({ data: { semesterId: semester.id, name: `${semester.department.name} - Semester ${number}` } }); await ensureRoomChannels(room.id); res.status(201).json({ ...semester, room }); } catch (e) { next(e); } };
export const updateSemester = async (req: Request, res: Response, next: NextFunction) => { try { if (!validId(res, req.params.id)) return; const data: { number?: number; isActive?: boolean } = {}; if (req.body.number !== undefined) { const number = Number(req.body.number); if (!Number.isInteger(number) || number < 1) return fail(res, "Valid semester number is required"); data.number = number; } if (typeof req.body.isActive === "boolean") data.isActive = req.body.isActive; res.json(await prisma.semester.update({ where: { id: req.params.id! }, data })); } catch (e) { next(e); } };

export const listChannelsAdmin = async (req: Request, res: Response, next: NextFunction) => { try { const roomId = req.query.roomId as string | undefined; res.json(await prisma.channel.findMany({ where: roomId ? { roomId } : {}, include: { room: { include: { semester: { include: { department: true } } } }, _count: { select: { messages: true } } }, orderBy: [{ roomId: "asc" }, { position: "asc" }] })); } catch (e) { next(e); } };
export const createChannel = async (req: Request, res: Response, next: NextFunction) => { try { const roomId = text(req.body.roomId), name = text(req.body.name).replace(/^#/, "").toLowerCase(), description = text(req.body.description) || null; if (!isValidUuid(roomId) || !/^[a-z0-9-]{1,60}$/.test(name)) return fail(res, "Use a room and a channel name with lowercase letters, numbers, or hyphens"); const position = await prisma.channel.count({ where: { roomId } }); res.status(201).json(await prisma.channel.create({ data: { roomId, name, description, position } })); } catch (e) { next(e); } };
export const updateChannel = async (req: Request, res: Response, next: NextFunction) => { try { if (!validId(res, req.params.id)) return; const data: { name?: string; description?: string | null; position?: number; isActive?: boolean } = {}; if (req.body.name !== undefined) { const name = text(req.body.name).replace(/^#/, "").toLowerCase(); if (!/^[a-z0-9-]{1,60}$/.test(name)) return fail(res, "Invalid channel name"); data.name = name; } if (req.body.description !== undefined) data.description = text(req.body.description) || null; if (Number.isInteger(req.body.position)) data.position = req.body.position; if (typeof req.body.isActive === "boolean") data.isActive = req.body.isActive; res.json(await prisma.channel.update({ where: { id: req.params.id! }, data })); } catch (e) { next(e); } };
export const deleteChannel = async (req: Request, res: Response, next: NextFunction) => { try { if (!validId(res, req.params.id)) return; const channel = await prisma.channel.findUnique({ where: { id: req.params.id! } }); if (!channel) return fail(res, "Channel not found", 404); if (["general", "exam-prep"].includes(channel.name)) return fail(res, "Default channels cannot be deleted; archive them instead"); await prisma.channel.delete({ where: { id: channel.id } }); res.status(204).end(); } catch (e) { next(e); } };

export const listUsers = async (req: Request, res: Response, next: NextFunction) => { try { const q = text(req.query.q); res.json(await prisma.user.findMany({ where: q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }] } : {}, select: { id: true, name: true, email: true, username: true, createdAt: true, isActive: true, university: true, department: true }, orderBy: { createdAt: "desc" } })); } catch (e) { next(e); } };
export const updateUserStatus = async (req: Request, res: Response, next: NextFunction) => { try { if (!validId(res, req.params.id) || typeof req.body.isActive !== "boolean") return fail(res, "isActive is required"); res.json(await prisma.user.update({ where: { id: req.params.id! }, data: { isActive: req.body.isActive }, select: { id: true, isActive: true } })); } catch (e) { next(e); } };
export const deleteMessage = async (req: Request, res: Response, next: NextFunction) => { try { if (!validId(res, req.params.id)) return; await prisma.message.delete({ where: { id: req.params.id! } }); res.status(204).end(); } catch (e) { next(e); } };
export const deleteResource = async (req: Request, res: Response, next: NextFunction) => { try { if (!validId(res, req.params.id)) return; await prisma.resource.delete({ where: { id: req.params.id! } }); res.status(204).end(); } catch (e) { next(e); } };
